version: '3.7'
services:
  server:
    build: .
    command: uvicorn api.server:app --host 0.0.0.0 --port 8000 --reload --workers 1
    volumes: 
      - .:/loccumapi-fastapi
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    
volumes:
    postgres_data:
